In [59]:
# read dataframe
import pandas as pd

dataframe = pd.read_csv('../digits/train.csv', header=None, skiprows=1)

dataframe

,0,1,2,3,4,5,6,7,8,9,...,4087,4088,4089,4090,4091,4092,4093,4094,4095,4096
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0
1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0
2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0
3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0
4,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19994,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9
19995,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9
19996,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9
19997,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9
19998,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9

In [60]:
# split train and test values

from sklearn.model_selection import train_test_split
from keras.utils import to_categorical

X = dataframe.values[:,:-1]

y = dataframe.values[:, -1]
y = to_categorical(y)

X_train, X_test, y_train, y_test = train_test_split(
  X,
  y,
  test_size=0.2,
  # random_state=42,
  shuffle=True,
  stratify=y
)

In [61]:
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, InputLayer
from keras.initializers import RandomNormal

model = Sequential([
  InputLayer(input_shape=(4096,)),
  Dense(256, activation='relu', kernel_initializer=RandomNormal()),
  Dense(128, activation="sigmoid", kernel_initializer=RandomNormal()),
  Dense(10, activation='softmax')
])

model.compile(
  loss="categorical_crossentropy",
  optimizer="rmsprop",
  metrics=["categorical_accuracy"]
)

model.fit(
  X_train, 
  y_train,
  epochs=10,
  validation_split=0.2
)

model.evaluate(X_test, y_test)

Epoch 1/10
400/400 [==============================] - 2s 5ms/step - loss: 0.4143 - categorical_accuracy: 0.8759 - val_loss: 0.1670 - val_categorical_accuracy: 0.9494
Epoch 2/10
400/400 [==============================] - 2s 5ms/step - loss: 0.1308 - categorical_accuracy: 0.9615 - val_loss: 0.1345 - val_categorical_accuracy: 0.9647
Epoch 3/10
400/400 [==============================] - 2s 5ms/step - loss: 0.0987 - categorical_accuracy: 0.9694 - val_loss: 0.2205 - val_categorical_accuracy: 0.9347
Epoch 4/10
400/400 [==============================] - 2s 5ms/step - loss: 0.0803 - categorical_accuracy: 0.9746 - val_loss: 0.0793 - val_categorical_accuracy: 0.9759
Epoch 5/10
400/400 [==============================] - 2s 5ms/step - loss: 0.0617 - categorical_accuracy: 0.9797 - val_loss: 0.0756 - val_categorical_accuracy: 0.9787
Epoch 6/10
400/400 [==============================] - 2s 5ms/step - loss: 0.0595 - categorical_accuracy: 0.9816 - val_loss: 0.0786 - val_categorical_accuracy: 0.9750
Epoch 7/10
400/400 [==============================] - 2s 5ms/step - loss: 0.0467 - categorical_accuracy: 0.9856 - val_loss: 0.0723 - val_categorical_accuracy: 0.9819
Epoch 8/10
400/400 [==============================] - 2s 5ms/step - loss: 0.0401 - categorical_accuracy: 0.9864 - val_loss: 0.0693 - val_categorical_accuracy: 0.9828
Epoch 9/10
400/400 [==============================] - 2s 5ms/step - loss: 0.0337 - categorical_accuracy: 0.9898 - val_loss: 0.0761 - val_categorical_accuracy: 0.9800
Epoch 10/10
400/400 [==============================] - 2s 5ms/step - loss: 0.0315 - categorical_accuracy: 0.9887 - val_loss: 0.0561 - val_categorical_accuracy: 0.9869
125/125 [==============================] - 0s 1ms/step - loss: 0.0687 - categorical_accuracy: 0.9805

[0.06867261976003647, 0.9804999828338623]